In [109]:
from timeit import repeat
import numpy as np
import matplotlib.pyplot as plt
from collections import deque

In [116]:
def sundaram_naive_boolean(n):
    m = n//2
    L = [True] * n
    
    for i in range(1, m):
        L[2*i] = False
        for j in range(1, m):
            U = i + j + 2*i*j
            if U < m:
                L[2*U+1] = False

    L[0], L[1] = False, False
    L[2] = True
    return np.array([i for i, l in enumerate(L) if l])

In [117]:
sundaram_naive_boolean(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [112]:
def sundaram_naive_set(n):
    m = n // 2
    L = {l for l in range(1,m)}
    for i in range(1,m):
        for j in range(i,m):
            U = i + j + 2*i*j
            if U < m:
                L.discard(U)
    primes = deque([2*l+1 for l in L])
    primes.extendleft([2])
    return np.array(primes)

In [122]:
def sundaram_optimized_set(n):
    m = n // 2
    L = {l for l in range(1,m)}
    for i in range(1,m):
        limit = (m-i)//(2*i+1)
        for j in range(i, limit+1):
            U = i + j + 2*i*j
            L.discard(U)
    primes = deque([2*l+1 for l in L])
    primes.extendleft([2])
    return np.array(primes)

array([      2,       3,       5, ..., 9999971, 9999973, 9999991])

In [119]:
def sundaram_optimized_boolean(n):
    m = n//2
    L = [True] * n
    
    for i in range(1, m):
        L[2*i] = False
        limit = (m-i)//(2*i+1)
        for j in range(i, limit+1):
            U = i + j + 2*i*j
            if U < m:
                L[2*U+1] = False

    L[0], L[1], L[2] = False, False, True
    return np.array([i for i, l in enumerate(L) if l])

In [120]:
sundaram_optimized_boolean(1000000)

array([     2,      3,      5, ..., 999961, 999979, 999983])